POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaXBlaUBleGFtcGxlLmNvbSIsImV4cCI6MTc2NjY2Njk1OCwidXNlcklkIjoxfQ.OpnJnDiy8iFX8TJr5FKavel-42o4_3nfInyKpB16TOk


{
  "name": "Test event",
  "description": "Test event",
  "location": "Test event",
  "dateTime": "2025-01-01T15:30:00.000Z"
}