POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaXBlaTFAZXhhbXBsZS5jb20iLCJleHAiOjE3Njg1Nzc4NTIsInVzZXJJZCI6M30.F9mPtEOTbv8_l1RjYaPj_cuGN8KCsM4JW_yiSlNE7rU


{
  "name": "Test event",
  "description": "Test event",
  "location": "Test event",
  "dateTime": "2025-01-01T15:30:00.000Z"
}