POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaXBlaUBleGFtcGxlLmNvbSIsImV4cCI6MTc2NjY5MDU3OCwidXNlcklkIjoxfQ.moWQ77F_9Rn02ZE8Xb6KHxGpqXVhI1FE0HooZZAI4Uc


{
  "name": "Test event",
  "description": "Test event",
  "location": "Test event",
  "dateTime": "2025-01-01T15:30:00.000Z"
}