POST http://localhost:8080/login
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaXBlaUBleGFtcGxlLmNvbSIsImV4cCI6MTc2NjY5MDU3OCwidXNlcklkIjoxfQ.moWQ77F_9Rn02ZE8Xb6KHxGpqXVhI1FE0HooZZAI4Uc

{
  "email": "taipei@example.com",
  "password": "123456"
}