POST http://localhost:8080/events/7/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaXBlaUBleGFtcGxlLmNvbSIsImV4cCI6MTc2NjY2NzM4OCwidXNlcklkIjoxfQ.5WfvbsJ7P9OMdawuAqpAmuX6uTvhp1-w2dLD5rKLqaI