POST http://localhost:8080/events/3/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhaXBlaUBleGFtcGxlLmNvbSIsImV4cCI6MTc2NjIxODM1MCwidXNlcklkIjoxfQ.ml-51M1EfirNDkPhm9Wkivc1dR9yoASD-be2KOaSoL0