name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 模擬部署前的檢查：確保 Dockerfile 在雲端環境也能成功 Build
    - name: Build the Docker image
      run: docker build -t test-build .
